/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan_mobil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MenuBayarCicilan extends javax.swing.JFrame {

    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();

    /**
     * Creates new form MenuDataMobil
     */
    public MenuBayarCicilan() {
        initComponents();
        k.connect();
        Tampiltabel();
        ComboKredit();

    }

    class cicilan {

        String kodecicilan, kodekredit, tanggal;
        int cicilan, tenor, cicilanke, sisacicil, totalcicil, sisaharga;

        public cicilan() throws Exception {
            this.kodecicilan = textkode.getText();
            String combo = cbkodekredit.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.kodekredit = arr[0];

            try {
                Date data = datecicilan.getDate();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                this.tanggal = df.format(data);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            PreparedStatement ps = k.getCon().prepareStatement("Select bayar_kredit,tenor,totalcicil from kredit "
                    + "WHERE kode_kredit=?");
            ps.setString(1, kodekredit);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                this.cicilan = rs.getInt("bayar_kredit");
                this.tenor = rs.getInt("tenor");
                this.totalcicil = rs.getInt("totalcicil");
            } else {
                throw new Exception("Data Tidak Bisa ditemukan!");
            }

            //hitung cicilan ke-
            ps = k.getCon().prepareStatement("SELECT COUNT(*) AS total FROM bayar_cicilan "
                    + "WHERE kode_kredit=? ");
            ps.setString(1, kodekredit);
            rs = ps.executeQuery();
            if (rs.next()) {
                this.cicilanke = rs.getInt("total") + 1;
            } else {
                this.cicilanke = 1;
            }
            this.sisacicil = tenor - cicilanke;
            this.sisaharga = totalcicil - (cicilanke * cicilan);
        }
    }

    public void Tampiltabel() {
        model = new DefaultTableModel();
        model.addColumn("Kode Cicilan");
        model.addColumn("Kode Kredit");
        model.addColumn("Tanggal");
        model.addColumn("Cicilan Ke-");
        model.addColumn("Besar Cicilan");
        model.addColumn("Sisa Cicilan");
        model.addColumn("Sisa Harga");
        tblcicilan.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("Select * from bayar_cicilan");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getInt(4),
                    rs.getInt(5),
                    rs.getInt(6),
                    rs.getInt(7),};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textkode.setText("");
    }

    public void ComboKredit() {
        try {
            this.stat = k.getCon().prepareStatement("Select * from kredit");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                cbkodekredit.addItem(rs.getString("kode_kredit") + ":"
                        + rs.getString("ktp") + ":"
                        + rs.getString("kode_paket") + ":"
                        + rs.getString("kode_mobil") + ":"
                        + rs.getString("tanggal_kredit") + ":"
                        + rs.getString("bayar_kredit") + ":"
                        + rs.getString("tenor") + ":"
                        + rs.getString("totalcicil"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnkembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textkode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcicilan = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbkodekredit = new javax.swing.JComboBox<>();
        datecicilan = new com.toedter.calendar.JDateChooser();
        textjumlah = new javax.swing.JTextField();
        textsisa = new javax.swing.JTextField();
        textcicilan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Bayar Cicilan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 190, 23));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Cicilan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 57, 77, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kode Kredit");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 88, 77, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cicilan ke-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, 77, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Cicilan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 140, 84, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sisa Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 175, -1, -1));

        textkode.setOpaque(false);
        textkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textkodeActionPerformed(evt);
            }
        });
        getContentPane().add(textkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 54, 305, -1));

        tblcicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcicilanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcicilan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 319, 375, 275));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 265, -1, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 265, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 265, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Cicilan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 216, -1, -1));

        getContentPane().add(cbkodekredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 85, 300, -1));
        getContentPane().add(datecicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 210, 305, -1));
        getContentPane().add(textjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 137, 305, -1));
        getContentPane().add(textsisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 172, 305, -1));

        textcicilan.setText(" ");
        getContentPane().add(textcicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 111, 305, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan_mobil/neon-background2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textkodeActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new MenuUtama(1).show();
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        try {
            cicilan c = new cicilan();
            this.stat = k.getCon().prepareStatement("insert into bayar_cicilan values(?,?,?,?,?,?,?)");
            stat.setString(1, c.kodecicilan);
            stat.setString(2, c.kodekredit);
            stat.setString(3, c.tanggal);
            stat.setInt(4, c.cicilanke);
            stat.setInt(5, c.cicilan);
            stat.setInt(6, c.sisacicil);
            stat.setInt(7, c.sisaharga);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ini adalah cicilan ke-" + c.cicilanke
                    + "\nSisa Cicilan " + c.sisacicil + " kali\nSisa Harganya Rp." + c.sisaharga);
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e.getMessage());
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblcicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcicilanMouseClicked
        int row = tblcicilan.getSelectedRow();
        textkode.setText(model.getValueAt(row, 0).toString());
        String Kredit = model.getValueAt(row, 1).toString();
        for (int i = 0; i < cbkodekredit.getItemCount(); i++) {
            if (cbkodekredit.getItemAt(i).startsWith(Kredit + ":")) {
                cbkodekredit.setSelectedIndex(i);
                break;
            }
        }
        try {
            String tanggal = model.getValueAt(row, 2).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            Date date = sdf.parse(tanggal);
            datecicilan.setDate(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblcicilanMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
         try {
            cicilan c = new cicilan();
            this.stat = k.getCon().prepareStatement("update bayar_cicilan set kode_kredit=?,tanggal_cicilan=?,"
                    + "cicilanke=?,jumlah_cicilan=?,sisa_cicilan=?,sisaharga=? where kode_cicilan=?");
            stat.setString(1, c.kodekredit);
            stat.setString(2, c.tanggal);
            stat.setInt(3, c.cicilanke);
            stat.setInt(4, c.cicilan);
            stat.setInt(5, c.sisacicil);
            stat.setInt(6, c.sisaharga);
            stat.setString(7, c.kodecicilan);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ini adalah cicilan ke-" + c.cicilanke
                    + "\nSisa Cicilan " + c.sisacicil + " kali\nSisa Harganya Rp." + c.sisaharga);
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            cicilan c = new cicilan();
            this.stat=k.getCon().prepareStatement("delete from bayar_cicilan where kode_cicilan=?");
            stat.setString(1, textkode.getText());
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBayarCicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBayarCicilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbkodekredit;
    private com.toedter.calendar.JDateChooser datecicilan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcicilan;
    private javax.swing.JTextField textcicilan;
    private javax.swing.JTextField textjumlah;
    private javax.swing.JTextField textkode;
    private javax.swing.JTextField textsisa;
    // End of variables declaration//GEN-END:variables
}
