/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan_mobil;

import java.io.File;
import java.nio.file.Files;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MenuDataMobil extends javax.swing.JFrame {

    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();
    private String selectedImagepath="";
    
    public MenuDataMobil() {  
        initComponents();
        k.connect();
        Tampiltabel();
    }
    
    class mobil extends MenuDataMobil{
        String kode,merk,type,warna,gambar;
        int harga;
        
        public mobil(){
            this.kode=textkode.getText();
            this.merk=textmerk.getText();
            this.type=texttype.getText();
            this.warna=textwarna.getText();
            this.harga=Integer.parseInt(textharga.getText());
            this.gambar=selectedImagepath;
        }
    }
    public void Tampiltabel(){
        model=new DefaultTableModel();
        model.addColumn("Kode");
        model.addColumn("Merk");
        model.addColumn("Type");
        model.addColumn("Warna");
        model.addColumn("Harga");
        model.addColumn("Gambar Mobil");
        tblmobil.setModel(model);
        
        try {
            this.stat=k.getCon().prepareStatement("Select * From mobil");
            this.rs=this.stat.executeQuery();
            while(rs.next()){
                Object[] data={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getInt(5),
                    rs.getString(6)
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textkode.setText("");
        textharga.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnkembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelgambar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textkode = new javax.swing.JTextField();
        textmerk = new javax.swing.JTextField();
        texttype = new javax.swing.JTextField();
        textwarna = new javax.swing.JTextField();
        textharga = new javax.swing.JTextField();
        btngambar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmobil = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Halaman Data Mobil");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 210, 23));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Mobil");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 57, 77, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Merk Mobil");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 88, 77, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type Mobil");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 119, 77, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Warna Mobil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 150, 77, -1));

        labelgambar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelgambar.setForeground(new java.awt.Color(255, 255, 255));
        labelgambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelgambar.setText("Gambar Mobil");
        getContentPane().add(labelgambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 120));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Mobil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 185, 77, 20));

        textkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textkodeActionPerformed(evt);
            }
        });
        getContentPane().add(textkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 54, 305, -1));

        textmerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmerkActionPerformed(evt);
            }
        });
        getContentPane().add(textmerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 85, 305, -1));

        texttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttypeActionPerformed(evt);
            }
        });
        getContentPane().add(texttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 116, 305, -1));

        textwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textwarnaActionPerformed(evt);
            }
        });
        getContentPane().add(textwarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 147, 305, -1));

        textharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaActionPerformed(evt);
            }
        });
        getContentPane().add(textharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 182, 305, -1));

        btngambar.setText("Pilih Gambar");
        btngambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngambarActionPerformed(evt);
            }
        });
        getContentPane().add(btngambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 380, 20));

        tblmobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmobil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 425, 375, 180));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 120, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 390, 110, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan_mobil/neon-background2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textkodeActionPerformed

    private void textmerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textmerkActionPerformed

    private void texttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttypeActionPerformed

    private void textwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textwarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textwarnaActionPerformed

    private void texthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
       new MenuUtama(1).show();
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
            mobil m=new mobil();
            String newFileName="";
            if (!m.gambar.equals("")) {
                File sourceFile= new File(m.gambar);
                File destDir= new File("uploads");
                if (!destDir.exists())destDir.mkdir();
                newFileName="uploads/"+sourceFile.getName();
                Files.copy(sourceFile.toPath(), new File(newFileName).toPath());    
            }
            this.stat=k.getCon().prepareStatement("insert into mobil values(?,?,?,?,?,?)");
            stat.setString(1, m.kode);
            stat.setString(2, m.merk);
            stat.setString(3, m.type);
            stat.setString(4, m.warna);
            stat.setInt(5, m.harga);
            stat.setString(6, newFileName);
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblmobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmobilMouseClicked
        textkode.setText(model.getValueAt(tblmobil.getSelectedRow(), 0).toString());
        textmerk.setText(model.getValueAt(tblmobil.getSelectedRow(), 1).toString());
        texttype.setText(model.getValueAt(tblmobil.getSelectedRow(), 2).toString());
        textwarna.setText(model.getValueAt(tblmobil.getSelectedRow(), 3).toString());
        textharga.setText(model.getValueAt(tblmobil.getSelectedRow(), 4).toString());
        selectedImagepath=model.getValueAt(tblmobil.getSelectedRow(), 5).toString();
        if(selectedImagepath!=null && !selectedImagepath.isEmpty()){
            ImageIcon icon=new ImageIcon(new ImageIcon(selectedImagepath).getImage().getScaledInstance(200, 120, java.awt.Image.SCALE_SMOOTH));
            labelgambar.setIcon(icon);
        }
        else {
            labelgambar.setIcon(null);
        }
    }//GEN-LAST:event_tblmobilMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try {
            mobil m=new mobil();
            String newFileName="";
            if (!m.gambar.equals("")) {
                File sourceFile= new File(m.gambar);
                File destDir= new File("uploads");
                if (!destDir.exists())destDir.mkdir();
                newFileName="uploads/"+sourceFile.getName();
                Files.copy(sourceFile.toPath(), new File(newFileName).toPath());
            }
            this.stat=k.getCon().prepareStatement("update mobil set merk=?,"+
                    "type=?,warna=?,harga=?,gambar=? where kode_mobil=?");
            stat.setString(1, m.merk);
            stat.setString(2, m.type);
            stat.setString(3, m.warna);
            stat.setInt(4, m.harga);
            stat.setString(5, newFileName);
            stat.setString(6,textkode.getText());
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            mobil m=new mobil();
            this.stat=k.getCon().prepareStatement("delete from mobil where kode_mobil=?");
            stat.setString(1, textkode.getText());
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btngambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngambarActionPerformed
        JFileChooser chooser= new JFileChooser();
        int option = chooser.showOpenDialog(this);
        if (option==JFileChooser.APPROVE_OPTION) {
            File file=chooser.getSelectedFile();
            selectedImagepath=file.getAbsolutePath();
            JOptionPane.showMessageDialog(this, "Gambar yang dipilih:"+selectedImagepath);
        }
    }//GEN-LAST:event_btngambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDataMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngambar;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelgambar;
    private javax.swing.JTable tblmobil;
    private javax.swing.JTextField textharga;
    private javax.swing.JTextField textkode;
    private javax.swing.JTextField textmerk;
    private javax.swing.JTextField texttype;
    private javax.swing.JTextField textwarna;
    // End of variables declaration//GEN-END:variables
}
