/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan_mobil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MenuBeliCash extends javax.swing.JFrame {

    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    Koneksi k = new Koneksi();

    /**
     * Creates new form MenuDataMobil
     */
    public MenuBeliCash() {
        initComponents();
        k.connect();
        Tampiltabel();
        ComboMobil();
        ComboPembeli();
    }

    class cash extends MenuBeliCash {

        String kode_cash, noktp, nama, kodemobil, merk, tipe, warna, cash_tgl;
        int cash_bayar, harga;

        public cash() {
            this.kode_cash = textkode.getText();
            String combo1 = cbktp.getSelectedItem().toString();
            String[] arr = combo1.split(";");
            this.noktp = arr[0];

            String combo2 = cbkdmobil.getSelectedItem().toString();
            String[] arr1 = combo2.split(":");
            this.kodemobil = arr1[0].split(";")[0];  // "M001"                  // "Silver"
            this.harga = Integer.parseInt(arr1[3]);  // 200000000
            try {
                Date date = datetanggal.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.cash_tgl = dateformat.format(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }

    public void Tampiltabel() {
        model = new DefaultTableModel();
        model.addColumn("Kode");
        model.addColumn("KTP");
        model.addColumn("Kode Mobil");
        model.addColumn("Tanggal");
        model.addColumn("Total Bayar");
        tblcash.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("Select * from beli_cash");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getInt(5),};
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textkode.setText("");
        txtbayar.setText("");
    }

    public void ComboMobil() {
        try {
            this.stat = k.getCon().prepareStatement("Select * from mobil");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                cbkdmobil.addItem(rs.getString("kode_mobil") + ";"
                        + rs.getString("merk") + ":"
                        + rs.getString("type") + ":"
                        + rs.getString("warna") + ":"
                        + rs.getString("harga"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void ComboPembeli() {
        try {
            this.stat = k.getCon().prepareStatement("Select * from pembeli");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                cbktp.addItem(rs.getString("ktp") + ";"
                        + rs.getString("nama_pembeli")
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnkembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textkode = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcash = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        cbktp = new javax.swing.JComboBox<>();
        cbkdmobil = new javax.swing.JComboBox<>();
        datetanggal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaksi Penjualan Cash");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 23));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Cash");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 57, 77, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KTP Pembeli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 88, 77, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Mobil");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 119, 77, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Beli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 147, 77, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bayar (RP)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 182, 77, -1));

        textkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textkodeActionPerformed(evt);
            }
        });
        getContentPane().add(textkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 54, 305, -1));

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 179, 305, -1));

        tblcash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcash);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 319, 375, 275));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 243, -1, -1));

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 243, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 243, -1, -1));

        getContentPane().add(cbktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 85, 305, -1));

        cbkdmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkdmobilActionPerformed(evt);
            }
        });
        getContentPane().add(cbkdmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 116, 305, -1));
        getContentPane().add(datetanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 147, 305, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan_mobil/neon-background2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textkodeActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void cbkdmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkdmobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkdmobilActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new MenuUtama(1).show();
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        try {
            cash c = new cash();
            this.stat = k.getCon().prepareStatement("insert into beli_cash values(?,?,?,?,?)");
            stat.setString(1, c.kode_cash);
            stat.setString(2, c.noktp);
            stat.setString(3, c.kodemobil);
            stat.setString(4, c.cash_tgl);
            stat.setInt(5, c.harga);
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void tblcashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcashMouseClicked
        int row = tblcash.getSelectedRow();
        textkode.setText(model.getValueAt(row, 0).toString());

        String ktp = model.getValueAt(row, 1).toString();
        for (int i = 0; i < cbktp.getItemCount(); i++) {
            if (cbktp.getItemAt(i).startsWith(ktp + ":")) {
                cbktp.setSelectedIndex(i);
                break;
            }
        }

        try {
            String tanggal = model.getValueAt(row, 3).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            Date date = sdf.parse(tanggal);
            datetanggal.setDate(date);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblcashMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try {
            cash c = new cash();
            this.stat = k.getCon().prepareStatement("update beli_cash set ktp=?,"
                    + "kode_mobil=?, cash_tgl=?,cash_bayar=? where kode_cash=?");
            stat.setString(1, c.noktp);
            stat.setString(2, c.kodemobil);
            stat.setString(3, c.cash_tgl);
            stat.setInt(4, c.harga);
            stat.setString(5, c.kode_cash);
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            cash c = new cash();
            this.stat=k.getCon().prepareStatement("delete from beli_cash where kode_cash=?");
            stat.setString(1, textkode.getText());
            stat.executeUpdate();
            Tampiltabel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBeliCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBeliCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbkdmobil;
    private javax.swing.JComboBox<String> cbktp;
    private com.toedter.calendar.JDateChooser datetanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcash;
    private javax.swing.JTextField textkode;
    private javax.swing.JTextField txtbayar;
    // End of variables declaration//GEN-END:variables
}
